---
title: "GSEA_Microarray_Analysis"
author: "Juraj Adamik"
date: '2022-09-25'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(ballgown)
library(GSEABase)
# Currated
gs = geneIds(getGmt("..//c2.all.v2022.1.Hs.symbols.gmt"))

```

```{r}
###Download Genesets: http://www.gsea-msigdb.org/gsea/downloads.jsp
###Need to get the ranked list of genes (tt stand for top table from limma output)
ranks <- Good_iDCsBad_iDC$logFC
names(ranks) <- rownames(Good_iDCsBad_iDC)
head(ranks)
barplot(sort(ranks, decreasing = T))
###Load genesets and run FGSEA
fgseaRes_C2 <- fgsea(pathways = gs, stats = ranks, eps = 0.0)
```


```{r}
#saveRDS(fgseaRes_C2, ("../GSEA_Results/iDC_mDC_C2.RDs"))
fgseaRes_C2 %>% arrange(desc(NES))
fgseaRes_C2$pathway

###Make GSEA Figure
plotEnrichment(pathway = gs[["FIGUEROA_AML_METHYLATION_CLUSTER_4_UP"]], gseaParam = 1, ticksSize = 0.5, stats = ranks) +
  labs(title="GOBP XENOBIOTIC METABOLIC\nPROCESS") + theme(text = element_text(size = 24)) +
  labs(x = "Rank", y = "Enrichment Score")

plotEnrichment(gs[["HALLMARK_ESTROGEN_RESPONSE_EARLY"]], ranks)
```

# Hallmark
```{r}

gs = geneIds(getGmt("../GSEA/h.all.v2022.1.Hs.entrez.gmt"))
gs
fgseaRes_C2 <- fgsea(pathways = gs, stats = ranks, eps = 0.0)

saveRDS(fgseaRes_C2, ("../GSEA_Results/iDC_mDC_C2.RDs"))
fgseaRes_C2 %>% arrange(desc(NES))
fgseaRes_C2$pathway

###Make GSEA Figure
plotEnrichment(pathway = gs[["FIGUEROA_AML_METHYLATION_CLUSTER_4_UP"]], gseaParam = 1, ticksSize = 0.5, stats = ranks) +
  labs(title="GOBP XENOBIOTIC METABOLIC\nPROCESS") + theme(text = element_text(size = 24)) +
  labs(x = "Rank", y = "Enrichment Score")

plotEnrichment(pathwaysH[["HALLMARK_ESTROGEN_RESPONSE_EARLY"]], ranks)
```


```{r}


glimpse(fgseaRes_C2)
topPathways <- fgseaRes_C2 %>% 
    top_n(20, wt=-padj) %>% 
    arrange(-NES) %>% 
    pull(pathway)

dev.off()
plotGseaTable(gs[topPathways], 
              ranks, 
              fgseaRes_C2, 
              gseaParam = 0.5)
```


```{r}
fgseaRes_C2 %>% slice_max(padj, n = 30)
fgseaRes_C2 %>% slice_min(NES, n = 2)

rbind(fgseaRes_C2 %>% filter(NES > 2.5 & padj < 0.05)#, fgseaRes_C2 %>%  filter(NES < -1.75 & padj < 0.05)
      ) %>% 
  ggplot(aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill=padj<0.05)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA")

par(mfrow=c(1,2))

fgseaRes_C2 %>% filter(grepl(pattern = "TCA|LONG_CHAIN|FAO|GLYCOLYS|GLUCOSE", pathway)) %>% 
  ggplot(aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill=padj<0.05)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA")


```

```{r}
Metab_Path_Good_mDCvsGood_iDC <- fgseaRes_C2



pathway_Good <- Metab_Path_Good_mDCvsGood_iDC %>% filter(padj < 0.05) %>% pull(pathway) %>% 
  as.data.frame()
      
pathway_Bad <- fgseaRes_C2 %>% filter(padj < 0.05)


pathway_Bad <- rbind(fgseaRes_C2 %>% filter(NES > 2.5 & padj < 0.05)#, fgseaRes_C2 %>%  filter(NES < -1.75 & padj < 0.05)
      ) %>% pull(pathway)


bad.df <-  as.data.frame(pathway_Bad)

good.df <-  as.data.frame(pathway_Good)


pathway_Bad %>% filter(grepl(pattern = "IFN", pathway)) %>% pull(leadingEdge)

pathway_Bad$present <- pathway_Bad$pathway %in% pathway_Good$.
pathway_Bad %>% filter(padj < 0.05) %>% filter(present != "TRUE") %>% 
   #filter(NES > 1.75) %>% 
 # filter(grepl(pattern = "INTER|CYTOKINE", pathway)) %>% 
  ggplot(aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill=padj<0.05)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA")

pathway_Good %>% filter(padj < 0.05) %>% filter(present != "TRUE") %>% 
  filter(NES < 0)
  pull(pathway)
```

```{r}
# Load library
library(VennDiagram)
 
# Generate 3 sets of 200 words
set1 <- paste(rep("word_" , 200) , sample(c(1:1000) , 200 , replace=F) , sep="")
set2 <- paste(rep("word_" , 200) , sample(c(1:1000) , 200 , replace=F) , sep="")
set3 <- paste(rep("word_" , 200) , sample(c(1:1000) , 200 , replace=F) , sep="")
 
# Chart
venn.diagram(
  x = list(pathway_Good, pathway_Bad),
  category.names = c("Good" , "Bad"),
  filename = '#14_venn_diagramm.png',
  output=TRUE
)
```

